### ISSUE TITLE
No handling for exceeded quota

### ISSUE THREAD

**Issue by FunctionDJ** [XeynQ4/powercord-yt-search#1]
`data` inside `index.js` can be this
![image](https://user-images.githubusercontent.com/34871211/143722879-0270e0e9-6e9e-488c-85e0-48940c34b829.png)
which results in a 'Cannot read property '0' of undefined' error.

**Comment by XeynQ4** [comment]
Its cause you can use it only 100 times per day. Ill make the error more user friendly tomorrow.

**Comment by FunctionDJ** [comment]
I got this error immediately, i also tried creating a new project... maybe i did something wrong?

**Comment by XeynQ4** [comment]
Can you copy both messages for me so I can see them whole?

But its the quota error so it should be cause you exceeded your daily quota of 10000 points per day (my plugin uses 100 per command).

Rn I cant debug this but tomorrow ill take a look. Also maybe since the quota is daily it will work tomorrow

**Comment by FunctionDJ** [comment]
I added a line to log the data variable
![image](https://user-images.githubusercontent.com/34871211/143765591-dc9cb2c8-8eec-41e0-bea7-74c4d7d8eb68.png)

**Comment by XeynQ4** [comment]
For now, I made the errors more user friendly (I hope). Try to go to google developer console and in the project go to API tab and in the dashboard tab click on YouTube Data API v3. Click on the quotas tab and expand the queries. Check that all the limits are maxed out. If they are, than I don't know what's wrong.

**Comment by FunctionDJ** [comment]
@XeynQ4 This is how that page looks like.
![image](https://user-images.githubusercontent.com/34871211/143776664-2b50b977-6e90-40b6-bdf3-442bdf8807b7.png)
Below the "No data is available" it says "Quota has exceeded the amount of errors (3 hours) - Queries per day".
The first line of the table below says "Queries per day: 0" for some reason, which i can't edit. Maybe that's part of the issue?

**Comment by XeynQ4** [comment]
Yeah that's the issue. Idk why you can't edit it. I'll look into it.

**Comment by XeynQ4** [comment]
The only thing I found is if your project is 90 days inactive, google will set your quota limit. to zero. Maybe try making a new project with new API key. If that doesnt work, you could try logging into google developer console with another account and make project on it. Or I could dm you api key of my second account. I created it yesterday so if nothing will work just dm me on discord. My discord is Xeyn_Q4#3897. I will send you my API key that you should put in the settings.
